version: '2.1'
orbs:
  terraform: 'circleci/terraform@dev:alpha'
workflows:
  validate_infrastructure:
    jobs:
      - terraform/fmt:
          pre-steps:
            - checkout
            - run:
                command: "ls -l && pwd"
          checkout: true
          path: "./04_05_terraform_cloud_vcs/"
      - terraform/validate:
          checkout: true
          path: "./04_05_terraform_cloud_vcs/"
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          path: "./04_05_terraform_cloud_vcs/"
          requires:
            - terraform/validate
