version: 2

jobs:
  fmt:
    working_directory: /
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            terraform fmt -no-color -check -diff "/terraform"
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  fmt_plan_approve_apply:
    jobs:
      - fmt
      # - plan:
      #   requires:
      #     - fmt