version: 2

jobs:
  fmt:
    working_directory: /code
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: print cwd and list content
          command: pwd && ls
      - run:
          name: terraform fmt
          command: |
            terraform fmt -no-color -check -diff "./terraform"

  plan:
    working_directory: /code
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            pwd && ls
            cd ./environments/dev
            pwd && ls
            terraform init -input=false ../../terraform/
            terraform plan -out tfapply -var-file=dev.tfvars ../../terraform/
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
    - fmt 
    - plan:
        requires:
          - fmt