version: 2

jobs:
  fmt:
    working_directory: /tmp/app
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: print cwd and list content
          command: pwd && ls
      - run:
          name: terraform fmt
          command: |
            terraform fmt -no-color -check -diff "./terraform"

  plan:
    working_directory: /tmp/app
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd "./environments/dev"
            terraform init -input=false
            terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  post_plan:
    working_directory: /tmp/app
    docker:
      - image: hashicorp/terraform:light
    steps:
      - run:
          name: post plan check
          command: ls "./environments/dev"

workflows:
  version: 2
  fmt_plan_approve_apply:
    jobs:
      - fmt
      - plan:
        requires:
          - fmt
      - post_plan:
        requires:
          - plan