version: '2.1'
orbs:
  terraform: 'circleci/terraform@dev:alpha'
workflows:
  validate_infrastructure:
    jobs:
      - terraform/fmt:
          pre-steps:
            - checkout
            - run:
                command: "terraform version"
            - run:
                command: "ls -l && pwd"
          checkout: true
          path: "./terraform/"
      - terraform/validate:
          checkout: true
          path: "./terraform/"
          requires:
            - terraform/fmt
